import re
from typing import Dict, Optional, List, Tuple, Set, Any

class ProductExtractor:
    """
    Industrial E-Commerce Entity Resolution & Lexical Extraction Engine.
    Engineered with dedicated entity slotting: Brand, SKU, Model, Demographics,
    Color Profile, and Metrics to ensure 100% exact cross-store matches.
    """

    # 1. Structural Marketplace Pollution generated by Store Scraping
    MARKETPLACE_POLLUTION_REGEX = re.compile(
        r'(\s*\|\s*.*|\s*-\s*(flipkart|amazon|myntra|ajio|tata\s*cliq|nykaa).*|'
        r'\{.*?\}|\(.*?\)|\[.*?\]|"(?:by\s+[^"]+)"|"(?:from\s+[^"]+)"|'
        r'online\s+at\s+best\s+price.*|\bonline\s+shopping\b.*)',
        re.IGNORECASE
    )

    # 2. Strict SKU / Model-Code Regex (e.g. OGL-09, SM-S918B, GT-2000, Pegasus-40, 15-Pro)
    SKU_PATTERN = re.compile(
        r'\b(?:[A-Z]{1,5}[-_]?[0-9]{1,5}[A-Z0-9]*|[0-9]{1,4}[-_]?[A-Z]{1,5}[A-Z0-9]*)\b',
        re.IGNORECASE
    )

    # 3. Universal Variant Extractors (Footwear sizes, Fluid Volumes, Weight, Storage)
    VARIANT_PATTERNS = [
        (re.compile(r'\b(?:uk|us|eu|size)[\s:-]*([4-9]|1[0-2])\b', re.IGNORECASE), r'UK-\1'),
        (re.compile(r'(\d+(?:\.\d+)?)\s*(ml|l|fl\.?\s*oz|oz)\b', re.IGNORECASE), r'\1\2'),
        (re.compile(r'(\d+(?:\.\d+)?)\s*(g|gm|kg)\b', re.IGNORECASE), r'\1\2'),
        (re.compile(r'(\d+)\s*(gb|tb)\b', re.IGNORECASE), r'\1\2')
    ]

    # 4. Standard Product Color Dictionary (Preserved for SKU precision)
    COLOR_TERMS: Set[str] = {
        "white", "black", "blue", "red", "green", "grey", "gray", "yellow",
        "pink", "purple", "brown", "beige", "orange", "navy", "maroon",
        "olive", "teal", "silver", "gold", "tan", "cream"
    }

    # 5. Demographic Alignment
    GENDER_MAP = {
        "men": "Men", "mens": "Men", "male": "Men",
        "women": "Women", "womens": "Women", "female": "Women",
        "boys": "Boys", "girls": "Girls", "kids": "Kids", "unisex": "Unisex"
    }

    # 6. Commercial Fluff & Marketing Stopwords (Strictly non-identifying noise)
    LOW_SIGNAL_TOKENS: Set[str] = {
        "best", "trending", "latest", "original", "authentic", "official", "premium",
        "luxury", "classic", "stylish", "comfortable", "durable", "lightweight", "breathable",
        "pack", "combo", "set", "pair", "piece", "pcs", "exclusive", "edition", "series",
        "buy", "sale", "off", "free", "discount", "offer", "india", "online", "store",
        "lifestyle", "casual", "casuals", "corporate", "college", "sports", "running",
        "walking", "gym", "training", "wear", "daily", "regular", "fit", "flat",
        "memory", "foam", "insole", "pillofoam", "cushion", "cushioned", "sole",
        "gas", "no", "non", "lasting", "long", "hold",
        "for", "with", "without", "and", "in", "by", "from", "the", "an", "a", "of"
    }

    # 7. High-Authority Brands Database
    KNOWN_BRANDS: List[str] = [
        "red tape", "wild stone", "park avenue", "peter england", "louis philippe",
        "allen solly", "flying machine", "u.s. polo assn.", "us polo", "under armour",
        "nike", "adidas", "puma", "campus", "asian", "sparx", "reebok", "bata",
        "woodland", "asics", "skechers", "crocs", "axe", "fogg", "beardo", "nivea",
        "dove", "apple", "samsung", "boat", "noise", "sony", "oneplus", "realme",
        "fastrack", "casio", "titan", "mamaearth", "plum", "biotique"
    ]

    @classmethod
    def clean_raw_string(cls, text: str) -> str:
        if not text:
            return ""
        cleaned = cls.MARKETPLACE_POLLUTION_REGEX.sub(' ', text)
        cleaned = re.sub(r'[\'\"\|\(\)\[\]\{\}]', ' ', cleaned)
        return re.sub(r'\s+', ' ', cleaned).strip()

    @classmethod
    def split_fused_compounds(cls, text: str) -> str:
        """Splits sticky patterns like WhiteBlue -> White Blue, OGL09 -> OGL 09"""
        text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
        text = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1 \2', text)
        text = re.sub(r'([a-zA-Z])([0-9])', r'\1 \2', text)
        text = re.sub(r'([0-9])([a-zA-Z])', r'\1 \2', text)
        text = re.sub(r'[/\\_]', ' ', text)
        return text

    @classmethod
    def extract_variant(cls, text: str) -> Optional[str]:
        if not text:
            return None
        for pattern, replacement in cls.VARIANT_PATTERNS:
            match = pattern.search(text)
            if match:
                return match.expand(replacement).upper().replace(" ", "")
        return None

    @classmethod
    def resolve_brand(cls, text: str) -> Tuple[Optional[str], str]:
        text_lower = text.lower()
        for brand in cls.KNOWN_BRANDS:
            pattern = rf'\b{re.escape(brand)}\b'
            match = re.search(pattern, text_lower)
            if match:
                start, end = match.span()
                remainder = (text[:start] + " " + text[end:]).strip()
                return brand.title(), re.sub(r'\s+', ' ', remainder)
        return None, text

    @classmethod
    def clean_search_title(cls, raw_title: str) -> str:
        """Maintains backward compatibility while leveraging the full slot resolution."""
        data = cls.parse_metadata(raw_title)
        return data["clean_query"]

    @classmethod
    def parse_metadata(cls, raw_title: str) -> Dict[str, Any]:
        """
        Executes full entity extraction, producing isolated slots and a targeted search vector.
        """
        if not raw_title:
            return {
                "clean_query": "",
                "brand": None,
                "sku": None,
                "colors": [],
                "gender": None,
                "variant": None,
                "exact_descriptors": []
            }

        # Step 1: Normalize structural pollution & split sticky words
        clean_text = cls.clean_raw_string(raw_title)
        expanded_text = cls.split_fused_compounds(clean_text)

        # Step 2: Extract Variant (e.g. UK-8, 150ml)
        variant = cls.extract_variant(expanded_text)

        # Step 3: Extract Brand Anchor
        brand, remainder = cls.resolve_brand(expanded_text)

        # Normalize remainder tokens
        remainder_clean = re.sub(r'[^\w\s-]', ' ', remainder)
        tokens = [t.strip() for t in remainder_clean.split() if t.strip()]

        if not brand and tokens:
            brand = tokens[0].title()
            tokens = tokens[1:]

        # Step 4: Slot Sorting (Colors, Gender, SKU, High-Signal Nouns)
        detected_colors: List[str] = []
        detected_gender: Optional[str] = None
        sku_codes: List[str] = []
        core_nouns: List[str] = []

        for token in tokens:
            t_clean = token.strip("-_")
            t_lower = t_clean.lower()

            if len(t_clean) <= 1:
                continue

            # Check Gender
            if t_lower in cls.GENDER_MAP and not detected_gender:
                detected_gender = cls.GENDER_MAP[t_lower]
                continue

            # Check Colors
            if t_lower in cls.COLOR_TERMS:
                if t_lower.title() not in detected_colors:
                    detected_colors.append(t_lower.title())
                continue

            # Skip Low Signal Junk
            if t_lower in cls.LOW_SIGNAL_TOKENS:
                continue

            # Check SKU codes (e.g. OGL-09, Pegasus40)
            if cls.SKU_PATTERN.match(t_clean) and not t_lower.isdigit():
                sku_codes.append(t_clean)
            else:
                core_nouns.append(t_clean.title())

        # Step 5: High-Precision Search Vector Construction
        query_parts: List[str] = []
        if brand:
            query_parts.append(brand)

        if sku_codes:
            query_parts.append(sku_codes[0])
        elif core_nouns:
            query_parts.extend(core_nouns[:2])

        # Preserve color context so target stores open the identical hue
        if detected_colors:
            query_parts.append(" ".join(detected_colors[:2]))

        final_query = " ".join(query_parts).strip()
        if not final_query:
            final_query = clean_text[:40]

        return {
            "clean_query": final_query,
            "brand": brand,
            "sku": sku_codes[0] if sku_codes else None,
            "colors": detected_colors,
            "gender": detected_gender,
            "variant": variant,
            "exact_descriptors": core_nouns
        }

# Backwards compatibility alias
IndustrialProductExtractor = ProductExtractor